name: Tests

on:
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - ready_for_review

env:
  HATCH_VERSION: "1.14.0"
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9, '3.10', 3.11, 3.12]
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Hatch
        run: pip install hatch==${{ env.HATCH_VERSION }}

      - name: Run tests and generate coverage report
        run: hatch run test:cov
